dynamodb:
  production:
    endpoint-url: "http://dynamodb.us-west-1.amazonaws.com"
  test:
    endpoint-url: "http://localhost:8000"
  awws:
    metar-taf:
      table-name: "propeller_awws-metar-weather-report"
      partition-key: "location"
      sort-key: "datetime"
