name: Test AWS Setup in Isolation

on: [workflow_dispatch]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Start DynamoDB in GitHub Actions
      uses: rrainn/dynamodb-action@v3.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::832310466375:role/propeller-test-access
        aws-region: us-west-1

    - name: Do Something
      run: |
        echo "Something!"
