name: Ingestion Pipeline to write to DynamoDB

on:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  id-token: write

jobs:
  build-run-ingestion:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Remove default Chromium
      run: sudo apt purge chromium-browser

    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::832310466375:role/propeller-test-access
        aws-region: us-west-1

    - name: Execute Ingestion Pipeline
      run: python main_ingestion.py
