name: Test Source Files

on: [push]

permissions:
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint Code with Flake8
      run: |
        flake8 --max-line-length=120 ./src
        flake8 --max-line-length=120 ./test
    - name: Lint/Format Code with Black # https://black.readthedocs.io/en/stable/integrations/github_actions.html
      uses: psf/black@stable
      with:
        options: "--check --diff"
        src: "./src"
        version: "~= 22.0"

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Remove default Chromium
      run: sudo apt purge chromium-browser

    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Start DynamoDB in GitHub Actions
      uses: rrainn/dynamodb-action@v3.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::832310466375:role/propeller-test-access
        aws-region: us-west-1

    - name: Testing the Code with pytest
      run: |
        pytest -m "not expensive"