name: Test Source Files

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser
    - name: Testing the Code with pytest
      run: |
        pytest -m "not webtest"