name: Test Source Files

on: [push, pull_request]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Remove default Chromium
      run: sudo apt purge chromium-browser

    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Start DynamoDB in GitHub Actions
      uses: rrainn/dynamodb-action@v3.0.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::832310466375:role/propeller-test-access
        aws-region: us-west-1

    - name: Testing the Code with pytest
      run: |
        pytest -m "not expensive"